image: ubuntu:18.04
stages: 
  - test

format_test_stack:
  stage: test
    - node -v
    - npm install -g prettier


format_test_website:
  stage: test
    - cd website
    - npm install -g prettier


unit_test_stack:
  stage: test
  script:
    - npm install
    - npm run test


unit_test_website:
  stage: test
  script:
    - cd website
    - npm install
    - npm run test