image: ubuntu:18.04
stages: 
  - test

format_test_stack:
  stage: test
  script:
    - node -v
    - npm install -g prettier
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"


format_test_website:
  stage: test
  script:
    - cd website
    - npm install -g prettier
    - prettier --check  "src/**/*.ts"
    - prettier --check  "src/**/*.tsx"


unit_test_stack:
  stage: test
  script:
    - npm install
    - npm run test


unit_test_website:
  stage: test
  script:
    - cd website
    - npm install
    - npm run test