image: ubuntu:18.04
stages: 
  - test
unit_test:
  stage: test
  script:
    - apt-get update -qy
    - echo Y | apt-get install curl
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
    - source ~/.bashrc
    - source ~/.nvm/nvm.sh
    - nvm install 16
    - node -v
    - cd src
    - npm install
    - npm run test
# newman_test:
#   stage: test
#   script:
#     - apt-get update -qy
#     - echo Y | apt-get install curl
#     - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
#     - source ~/.bashrc
#     - source ~/.nvm/nvm.sh
#     - nvm install 16
#     - node -v
#     - npm install -g newman
#     - npm install -g forever
#     - cd src
#     - npm install
#     - forever start -c npm start
#     - newman run postman_tests.postman_collection.json
#     - forever stop start