image: ubuntu:18.04
stages: 
  - build
  - lint
  - test
  - deploy


stack_tests:
  stage: test
  script:
    - apt-get update -qy
    - echo Y | apt-get install curl
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
    - source ~/.bashrc
    - source ~/.nvm/nvm.sh
    - nvm install 16
    - node -v
    - npm install
    - npm run test


website_tests:
  stage: test
  script:
    - apt-get update -qy
    - echo Y | apt-get install curl
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
    - source ~/.bashrc
    - source ~/.nvm/nvm.sh
    - nvm install 16
    - node -v
    - npm install
    - npm run test
