image: ubuntu:18.04
stages: 
  - build
  - lint
  - test
  - deploy

build_job:
  stage: build
  script:
    - npm install
    - npm run build
    - cd website
    - npm install
    - npm run build

format_job:
  stage: lint
  script:
    - node -v
    - npm install -g prettier
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"
    - cd website
    - npm install -g prettier
    - prettier --check  "src/**/*.ts"
    - prettier --check  "src/**/*.tsx"

unit_test_job:
  stage: test
  script:
    - npm install
    - npm run test
    - cd website
    - npm install
    - npm run test

  
deployment_test:
  stage: deploy
  variables:
    ENVIRONMENT: "test"
  except:
    - main
  script:
    - echo "Deploying to '$ENVIRONMENT' Environment"
    - npm install
    - cd website
    - npm install
    - npm run build
    - cd ..
    - cdk synth
    - cdk deploy

deployment_production:
  stage: deploy
  variables:
    ENVIRONMENT: "production"
  only:
    - main
  script:
    - echo "Deploying to '$ENVIRONMENT' Environment"
    - npm install
    - cd website
    - npm install
    - npm run build
    - cd ..
    - cdk synth
    - cdk deploy
  