image: ubuntu:18.04
stages: 
  - build
  - test
  - deploy

build_stack:
  stage: build
  script:
    - npm install
    - npm run build
    - cd website
    - npm install
    - npm run build

format_test_stack:
  stage: test
  script:
    - node -v
    - npm install -g prettier
    - prettier --check  "lib/**/*.ts"
    - prettier --check  "bin/**/*.ts"

format_test_website:
  stage: test
  script:
    - cd website
    - npm install -g prettier
    - prettier --check  "src/**/*.ts"
    - prettier --check  "src/**/*.tsx"

unit_test_stack:
  stage: test
  script:
    - npm install
    - npm run test

unit_test_website:
  stage: test
  script:
    - cd website
    - npm install
    - npm run test

deployment:
  stage: deploy
  script:
    - npm install
    - cdk synth
    - cdk deploy